# This is a basic workflow to help you get started with Actions

name: SendVersionUpNotification

on:
  push:
    branches:
    - master
    paths:
    - 'versoin.yml'

  workflow_dispatch:
  
env:
  SLACK_WEBHOOK: ${{ secrets.SLACK_WEBHOOK_URL }}
  SLACK_USERNAME: DeployBot
  SLACK_CHANNEL: compe
  
jobs:
  notice:
    # The type of runner that the job will run on
    runs-on: ubuntu-latest

    # Steps represent a sequence of tasks that will be executed as part of the job
    steps:
      - name: Slack Notification on Version Changed
        uses: rtCamp/action-slack-notify@v2
        env:
          SLACK_TITLE: テスト
          SLACK_COLOR: good
